apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: <URL of your k8s-manifests repository>
    targetRevision: HEAD
  project: default
